version: "3"
services:

  # postgres set up
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - metadata_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB= playerIdentityService
    networks:
      - backend


volumes:
  metadata_data: {}

networks:
  backend: {}